"""empty message

Revision ID: bd837c2985e8
Revises: 7b8e0b8e38c6
Create Date: 2016-11-10 04:24:00.990624

"""

# revision identifiers, used by Alembic.
revision = 'bd837c2985e8'
down_revision = '7b8e0b8e38c6'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'points', 'accounts', ['account_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'points', type_='foreignkey')
    ### end Alembic commands ###
