"""empty message

Revision ID: e1d92b457bb0
Revises: f68cc3af0c0d
Create Date: 2016-09-02 14:48:35.011347

"""

# revision identifiers, used by Alembic.
revision = 'e1d92b457bb0'
down_revision = 'f68cc3af0c0d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('points', sa.Column('account_id', sa.BigInteger(), nullable=True))
    op.create_foreign_key(None, 'points', 'accounts', ['account_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'points', type_='foreignkey')
    op.drop_column('points', 'account_id')
    ### end Alembic commands ###
